name:                paypal-payout-check3
version:             0.1.0.0
github:              "githubuser/paypal-payout-check3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/paypal-payout-check3#readme>

dependencies:
- base >= 4.7 && < 5
- webdriver
- mtl
- random
- aeson
- text
- bytestring
- lens
- lens-aeson

library:
  source-dirs: src

executables:
  paypal-payout-check3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paypal-payout-check3

tests:
  paypal-payout-check3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paypal-payout-check3
    - hspec
