name:                paypal-payout-check3
version:             0.1.0.0
github:              "Vincibean/PayPal-Payout-Check"
license:             GPL-3.0
author:              "Vincibean"
maintainer:          "andrebessi00@gmail.com"
copyright:           "2020 Vincibean"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/Vincibean/PayPal-Payout-Check#readme>

dependencies:
- base >= 4.7 && < 5
- webdriver
- mtl
- random
- aeson
- text
- bytestring
- lens
- lens-aeson

library:
  source-dirs: src

executables:
  paypal-payout-check3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paypal-payout-check3

tests:
  paypal-payout-check3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paypal-payout-check3
    - hspec
    - directory
